FROM node:22 AS builder

WORKDIR /app

COPY demo/ .

RUN npm install

RUN npm run build

FROM ghcr.io/konfigo/konfigo-nginx:latest AS runner

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
